name: Bitcoin order App
on:
  push:
    branches:
      - master
      - feature/mlops-demo   # 👈 添加这一行
jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install puppeteer
        run: |
          npm install puppeteer --save-dev
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
          output-file: "false"
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Deploy
        run: |
          npm run deploy        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm ci
      - name: Build
        id: changelog
        run: |
          npm run test --watch=false --browsers=ChromeHeadlessCustom   # 👈 去掉末尾的双引号
      - name: Conventional Changelog Action
        run: |
          npm run lint
      - name: Test
          npm run build -- --prod
      - name: Lint
        run: |



